  base_template[m
  create_app_product[m
  create_form[m
  create_pages[m
  custom_model_managers[m
  detail[m
  featured_custom_querysets[m
  file_and_images_fields[m
  generate_project[m
  include_tag[m
  list_view[m
  login_register_forms[m
  lookups[m
  master[m
  pass_arguments_with_include[m
  product_urls[m
  reusable_list_view_snippets[m
* [32mreverse_url[m
  slug_field[m
  static_files[m
